### ISSUE TITLE
Abstract ILP solver with PULP

### ISSUE THREAD

**Issue by Erotemic** [morpheusthewhite/social-balance#1]
I took a look at the code, and it looks like you could write the optimization problem using [PULP](https://pypi.org/project/PuLP/) without any problems. Doing this would remove the hard dependency on Gurobi, and allow for use of FOSS solvers like [GLPK](https://www.gnu.org/software/glpk/glpk.html) or [COIN-OR CLP](https://github.com/coin-or/Clp) or using the higher quality commercial solvers (if you have the right license).

**Comment by morpheusthewhite** [comment]
I didn't know about that, thanks for suggesting it.

It is definitely something I'll do if this library offers all the features that I need (like branching priority and lazy constraints)

**Comment by morpheusthewhite** [comment]
As I expected some of the features optimizing the calculation are not available; nonetheless, the `pulp` branch replaces gurobi with this library
